version: "3"
services:
  db:
    image: postgres:15
    container_name: noticall-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noticall
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
